# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.16.1

pipelines:
  branches:
    develop:
      - step:
          caches:
            - node
          script:
            - pipe: atlassian/ssh-run:0.2.6
              variables:
                SSH_USER: 'marketplaceadm'
                SERVER: '34.206.48.173'
                COMMAND: '~/apis/deploy.sh'
                MODE: 'command'
                PORT: '22'
      - step:
          caches:
            - node
          script:
            - pipe: atlassian/ssh-run:0.2.6
              variables:
                SSH_USER: 'marketplaceadm'
                SERVER: '54.210.174.148'
                COMMAND: '~/apis/deploy.sh'
                MODE: 'command'
                PORT: '22'

